wIslandInfo:
  database:
    host:
    port:
    database:
    username:
    password:
settings:
  points-end: 800
  world-name: "world"
  rebound-cooldown: 500 # Milliseconds
messages:
  missing-points: "&c&lI'm sorry but you need more points to teleport to the end."
random-locations:
  1:
    x:
    y:
    z:
  2:
    x:
    y:
    z:
  # ... for as many locations as you need
