name: PortalRedirect
version: '${project.version}'
main: me.otisps.portalredirect.PortalRedirect
api-version: 1.18
authors: [ otisps ]
description:
depend: [WorldGuard]
commands:
  portalredirectreload:
    description: reloads config op or console only
    aliases: prreload